### ISSUE TITLE
running consult

### ISSUE THREAD

**Issue by hickey23** [jacobjj/motion_planning_transformer#1]
Hello,I downloaded your docker and tried to run it according to your instructions, but I found that I couldn't run your code. Do I need some other operations after I download the docker you provided? Maybe put Python files in that directory or something else
(please forgive me for my doubts when I just started Linux. Thank you for your answer)

**Comment by jacobjj** [comment]
Could you share the error?

**Comment by hickey23** [comment]
Thank you for your reply. In fact, after I download the docker container provided by you, I run "docker load - I mpt_container. Tar"   and it displays "loaded image: MPT: latest". Then I enter "docker run - it -- GPUs all -- SHM size =" 16g "- V ~ / global_planner_data: / root / data Bash" according to your prompt .    Then bash-5.1 #, which is displayed on the interface. 
 Since I just started Linux, I don't know if there are any errors.  Thank you again for your reply

**Comment by jimmydengpeng** [comment]
I got a same situation. Is there no Python3 interpreter in you docker image? Should I install a Python3 interpreter from source by myself? @jacobjj

**Comment by jacobjj** [comment]
@hickey23 , you also need to attach the code base to the container. 

@jimmydengpeng , please use `python3` instead of `python`.

**Comment by jimmydengpeng** [comment]
Seems like that there missed the 'mpt' parameter in the commad of Your README.md doc:
> docker run -it --gpus all --shm-size="16G" -v ~/global_planner_data:/root/data -v <link-to-code-base>:/workspace bash
I tried to add the 'mpt' and it worked successfully:
> docker run -it --gpus all --shm-size="16G" -v ~/global_planner_data:/root/data -v <link-to-code-base>:/workspace mpt bash
@jacobjj

**Comment by hickey23** [comment]
thank you ! I got it ! @jacobjj
