### ISSUE TITLE
项目部署调试可以联系我

### ISSUE THREAD

**Issue by fengmumu123123** [jacobjj/motion_planning_transformer#6]
成功在ubuntu22 大量修复后成功安装   
如需要可以在微信上联系我
![吴少华](https://github.com/jacobjj/motion_planning_transformer/assets/87262609/66890a45-012a-453b-814f-145b825dd2c4)
已下是运行截图
![image](https://github.com/jacobjj/motion_planning_transformer/assets/87262609/4dcc06d5-0f9b-4bc1-a033-ce24fc8a22fc)
![image](https://github.com/jacobjj/motion_planning_transformer/assets/87262609/31f9f6e3-94ef-486f-86c1-d9e73c4ebe45)
![image](https://github.com/jacobjj/motion_planning_transformer/assets/87262609/98646c4c-55e2-4b14-877b-e51ede24832a)
![image](https://github.com/jacobjj/motion_planning_transformer/assets/87262609/574d470e-3b84-499f-9578-759d95c1544d)

**Comment by fengmumu123123** [comment]
用了两天时间才解决这个陈年老项目 所以不会无偿服务

**Comment by jacobjj** [comment]
Thank you for the offer. This project is an open-source project, not meant to be commercialized.
